steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/photo-gallery-backend:$COMMIT_SHA', '.']

  # 2. Push the image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/photo-gallery-backend:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'photo-gallery-service' # <-- IMPORTANT: Must match your Cloud Run service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/photo-gallery-backend:$COMMIT_SHA'
      - '--region'
      - 'us-east1' # <-- IMPORTANT: Must match your Cloud Run region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/photo-gallery-backend:$COMMIT_SHA'